# syntax=docker/dockerfile:1
# build from scratch
# step 1: build golang binary
FROM golang
WORKDIR /opt/app
COPY . .
RUN go mod init main && go build -o ex1


# step 2: copy binary from step 1
FROM scratch
WORKDIR /opt/app
COPY --from=0 /opt/app/ex1 ./ex1
CMD ["/opt/app/ex1"]