# syntax=docker/dockerfile:1
# use alpine: 9.14MB
# step 1: build golang binary
FROM golang:alpine as builder
WORKDIR /opt/app
COPY . .
RUN go mod init main && go build -o ex1


# step 2: copy binary from step 1
FROM alpine:latest
WORKDIR /opt/app
COPY --from=builder /opt/app/ex1 ./ex1
CMD ["/opt/app/ex1"]