# syntax=docker/dockerfile:1
# two build stage image size 79.6MB
# add .dockerignore image size remain unchanged 79.6MB
# step 1: build golang binary
FROM golang:1.21 as builder
WORKDIR /opt/app
COPY . .
RUN go mod init main && go build -o ex1


# step 2: copy binary from step 1
FROM ubuntu:latest
WORKDIR /opt/app
COPY --from=builder /opt/app/ex1 ./ex1
CMD ["/opt/app/ex1"]