apiVersion: v1
kind: ConfigMap
metadata:
  name: vote-configmap
data:
#  OPTION_A: InfoQ
#  OPTION_B: GeekBang
#  REDIS_HOST: redis
  OPTION_A: {{ .Values.OPTION.OPTION_A }}
  OPTION_B: {{ .Values.OPTION.OPTION_B }}
  REDIS_HOST: {{ .Values.REDIS.HOST }}