apiVersion: v1
kind: Secret
metadata:
  name: yamltoinfra
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/vicchui/DevOpsCamp.git
  password: "" # your github personal access token
  username: vicchui
  insecure: "true"
  forceHttpBasicAuth: "true"
  enableLfs: "true"
