apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: vote-configmap
    literals:
      - OPTION_A=InfoQ
      - OPTION_B=GeekBang
      - REDIS_HOST=redis

secretGenerator:
  - name: result-db-secret
    files:
      - .env=.env
  - name: worker-db-secret
    files:
      - .env